package com.example.josh.akanyenyeri;

import java.io.Serializable;

/**
 * Created by JOSH on 7/22/2017.
 */
public class OPERATIONS implements Serializable {

    int ID_OPERATION;
    String NAME_OPERATION,TIER_PHONE_OPERATION,REASON_OPERATION,COMPANY_OPERATION;
    Double AMOUNT_OPERATION;
    String TIME_OPERATION,STATUS_OPERATION;

    public OPERATIONS(int ID_OPERATION, String NAME_OPERATION, String TIER_PHONE_OPERATION, String REASON_OPERATION, String COMPANY_OPERATION, Double AMOUNT_OPERATION, String TIME_OPERATION, String STATUS_OPERATION) {
        this.ID_OPERATION = ID_OPERATION;
        this.NAME_OPERATION = NAME_OPERATION;
        this.TIER_PHONE_OPERATION = TIER_PHONE_OPERATION;
        this.REASON_OPERATION = REASON_OPERATION;
        this.AMOUNT_OPERATION = AMOUNT_OPERATION;
        this.TIME_OPERATION = TIME_OPERATION;
        this.STATUS_OPERATION = STATUS_OPERATION;
        this.COMPANY_OPERATION = COMPANY_OPERATION;
    }
}
